# To mock a test failure, run: echo "faking an error " && exit 1

name: build_and_release

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - id: s001
              run: echo "github ${{ github.ref_name }}"
            - run: echo "before " && ls -l
            - id: s002
              uses: actions/setup-node@v4
              with:
                node-version: 22
            - id: s003
              run: echo "after " && ls -l
            # Required for GitHub Actions, not GitLab
            - id: s004
              uses: actions/checkout@v5
            # Install angular packages
            - id: s005
              run: npm i -g @angular/cli && npm ci && echo "Installed"
            - id: s006
              run: ng build
            - id: s007
              run: ls -l /dist/countingbook/browser
            - id: s008
              uses: nwtgck/actions-netlify@v3.0
              with:
                publish-dir: dist/countingbook/browser
                production-deploy: true
              env:
                NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
                NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
